version: "3.9"
services:
  postgres-learning:
    container_name: postgres-learning
    image: postgres:15.0-alpine
    environment:
      POSTGRES_DB: incubator-learn-db
      POSTGRES_USER: testUser
      POSTGRES_PASSWORD: testPassword
      PGDATA: "/var/lib/postgresql/data/.docker/pgdata"
    volumes:
      - ./.docker/postgres:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    build:
      context: "./.docker/postgres"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U testUser -d incubator-learn-db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - incubator-postgresql

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:7.0
    environment:
      PGADMIN_DEFAULT_EMAIL: "testUser@test.com"
      PGADMIN_DEFAULT_PASSWORD: "testPassword"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./.docker/pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - incubator-postgresql

  redis:
    image: redis:alpine
    container_name: redis-incubator
    command: redis-server --requirepass root
    volumes:
      - .:/data:delegated
    ports:
      - "36379:6379"
    expose:
      - "6379"
    networks:
      - incubator-postgresql
    restart: on-failure

networks:
  incubator-postgresql:
    driver: bridge

volumes:
  redis:
    driver: local
